//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApi.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaction
    {
        public int trans_id { get; set; }
        public int client_id { get; set; }
        public int acc_no { get; set; }
        public decimal trans_amount { get; set; }
        public string trans_description { get; set; }
        public string trans_type { get; set; }
        public string dr_cr { get; set; }
        public System.DateTime trans_date { get; set; }
    }
}
